### ISSUE TITLE
error: failed to run custom build command for `simdutf v0.2.0 (/Volumes/LaCie/code/git/simdutf-rs)`

### ISSUE THREAD

**Issue by Chacix** [Nugine/simdutf-rs#2]
error: failed to run custom build command for `simdutf v0.2.0 (/Volumes/LaCie/code/git/simdutf-rs)`

Caused by:
  process didn't exit successfully: `/Volumes/LaCie/code/git/simdutf-rs/target/debug/build/simdutf-b305ed2d17fca238/build-script-build` (exit status: 1)
  --- stdout
  TARGET = Some("x86_64-apple-darwin")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-apple-darwin")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
  running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-arch" "x86_64" "-Wall" "-Wextra" "-o" "/Volumes/LaCie/code/git/simdutf-rs/target/debug/build/simdutf-438ea27645bd60dd/out/cpp/simdutfrs.o" "-c" "cpp/simdutfrs.cpp"
  cargo:warning=In file included from cpp/simdutfrs.cpp:1:
  cargo:warning=In file included from cpp/simdutf.cpp:4:
  cargo:warning=cpp/simdutf.h:43:2: error: simdutf requires a compiler compliant with the C++11 standard
  cargo:warning=#error simdutf requires a compiler compliant with the C++11 standard
  cargo:warning= ^
  cargo:warning=cpp/simdutf.h:550:5: error: unknown type name 'constexpr'
  cargo:warning=    constexpr uint32_t pclmulqdq = uint32_t(1) << 1; ///< @private bit  1 of ECX for EAX=0x1
  cargo:warning=    ^
  cargo:warning=cpp/simdutf.h:550:23: error: expected ';' after top level declarator
  cargo:warning=    constexpr uint32_t pclmulqdq = uint32_t(1) << 1; ///< @private bit  1 of ECX for EAX=0x1
  cargo:warning=                      ^
  cargo:warning=                      ;
  cargo:warning=cpp/simdutf.h:551:5: error: unknown type name 'constexpr'
  cargo:warning=    constexpr uint32_t sse42 = uint32_t(1) << 20;    ///< @private bit 20 of ECX for EAX=0x1
  cargo:warning=    ^
  cargo:warning=cpp/simdutf.h:551:23: error: expected ';' after top level declarator
  cargo:warning=    constexpr uint32_t sse42 = uint32_t(1) << 20;    ///< @private bit 20 of ECX for EAX=0x1
  cargo:warning=                      ^
  cargo:warning=                      ;
  cargo:warning=cpp/simdutf.h:556:7: error: unknown type name 'constexpr'
  cargo:warning=      constexpr uint32_t bmi1 = uint32_t(1) << 3;
  cargo:warning=      ^
  cargo:warning=cpp/simdutf.h:556:25: error: expected ';' after top level declarator
  cargo:warning=      constexpr uint32_t bmi1 = uint32_t(1) << 3;
  cargo:warning=                        ^
  cargo:warning=                        ;
  cargo:warning=cpp/simdutf.h:557:7: error: unknown type name 'constexpr'
  cargo:warning=      constexpr uint32_t avx2 = uint32_t(1) << 5;
  cargo:warning=      ^
  cargo:warning=cpp/simdutf.h:557:25: error: expected ';' after top level declarator
  cargo:warning=      constexpr uint32_t avx2 = uint32_t(1) << 5;
  cargo:warning=                        ^
  cargo:warning=                        ;
  cargo:warning=cpp/simdutf.h:558:7: error: unknown type name 'constexpr'
  cargo:warning=      constexpr uint32_t bmi2 = uint32_t(1) << 8;
  cargo:warning=      ^
  cargo:warning=cpp/simdutf.h:558:25: error: expected ';' after top level declarator
  cargo:warning=      constexpr uint32_t bmi2 = uint32_t(1) << 8;
  cargo:warning=                        ^
  cargo:warning=                        ;
  cargo:warning=cpp/simdutf.h:559:7: error: unknown type name 'constexpr'
  cargo:warning=      constexpr uint32_t avx512f = uint32_t(1) << 16;
  cargo:warning=      ^
  cargo:warning=cpp/simdutf.h:559:25: error: expected ';' after top level declarator
  cargo:warning=      constexpr uint32_t avx512f = uint32_t(1) << 16;
  cargo:warning=                        ^
  cargo:warning=                        ;
  cargo:warning=cpp/simdutf.h:560:7: error: unknown type name 'constexpr'
  cargo:warning=      constexpr uint32_t avx512dq = uint32_t(1) << 17;
  cargo:warning=      ^
  cargo:warning=cpp/simdutf.h:560:25: error: expected ';' after top level declarator
  cargo:warning=      constexpr uint32_t avx512dq = uint32_t(1) << 17;
  cargo:warning=                        ^
  cargo:warning=                        ;
  cargo:warning=cpp/simdutf.h:561:7: error: unknown type name 'constexpr'
  cargo:warning=      constexpr uint32_t avx512ifma = uint32_t(1) << 21;
  cargo:warning=      ^
  cargo:warning=cpp/simdutf.h:561:25: error: expected ';' after top level declarator
  cargo:warning=      constexpr uint32_t avx512ifma = uint32_t(1) << 21;
  cargo:warning=                        ^
  cargo:warning=                        ;
  cargo:warning=cpp/simdutf.h:562:7: error: unknown type name 'constexpr'
  cargo:warning=      constexpr uint32_t avx512cd = uint32_t(1) << 28;
  cargo:warning=      ^
  cargo:warning=cpp/simdutf.h:562:25: error: expected ';' after top level declarator
  cargo:warning=      constexpr uint32_t avx512cd = uint32_t(1) << 28;
  cargo:warning=                        ^
  cargo:warning=                        ;
  cargo:warning=fatal error: too many errors emitted, stopping now [-ferror-limit=]
  cargo:warning=20 errors generated.
  exit status: 1

  --- stderr

  error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-arch" "x86_64" "-Wall" "-Wextra" "-o" "/Volumes/LaCie/code/git/simdutf-rs/target/debug/build/simdutf-438ea27645bd60dd/out/cpp/simdutfrs.o" "-c" "cpp/simdutfrs.cpp" with args "cc" did not execute successfully (status code exit status: 1).

**Comment by Nugine** [comment]
simdutf v0.2.1 is released. It should work now.
