### ISSUE TITLE
Got benchmarks?

### ISSUE THREAD

**Issue by lemire** [Nugine/simdutf-rs#4]
:-)

**Comment by Nugine** [comment]
This crate is a direct FFI binding of your awesome work [simdutf](https://github.com/simdutf/simdutf). 
Rust can call C/C++ functions without overhead. I think it does not need extra benchmarks for itself.

I'm also planning to compare `simdutf-rs` with other crates in Rust ecosystem. You can wait for a while until I have enough time to push forward it.

This issue is blocked by #3

**Comment by Nugine** [comment]
Adding benchmarks in https://github.com/Nugine/simd-benches

**Comment by Nugine** [comment]
In terms of UTF8 validation, simdutf seems to be slightly slower than [rusticstuff/simdutf8](https://github.com/rusticstuff/simdutf8).
See the section `utf8-check (GiB/s)` of [simd-benches](https://nugine.github.io/simd-benches/).

I am not sure whether the FFI boundaries block some optimizations.

**Comment by lemire** [comment]
> I am not sure whether the FFI boundaries block some optimizations.

There might be an overhead but you'd hope it is constant time (fixed overhead per function call).

This code...

```rust
pub fn validate_utf8(src: &[u8]) -> bool {
    let len = src.len();
    let buf = src.as_ptr();
    unsafe { crate::bindings::simdutf_validate_utf8(buf, len) }
}
```

```C++
bool simdutf_validate_utf8(const char *buf, size_t len) {
    return simdutf::validate_utf8(buf, len);
}
```

... might have a small overhead, but it is hard to imagine that it is much slower than calling `simdutf::validate_utf8(buf, len)`.

What happens if you grab simdutf on the machine and do...

```
wget https://ar.wikipedia.org/wiki/%D8%A7%D9%84%D9%85%D8%B1%D9%8A%D8%AE -O arabic.txt
cmake -B build
cmake --build build
sudo ./build/benchmarks/benchmark -P validate_utf8+haswell -F arabic.txt
```

The sudo is not strictly needed at the end, but if you do it and you have privileged access, it will give you some performance counters, which helps.


I am going to use an old AMD Rome server to be somewhat close to your processor...

```
$ sudo ./build/benchmarks/benchmark -P validate_utf8+haswell -F arabic.txt
[sudo] password for dlemire:
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as haswell
===========================
validate_utf8+haswell, input size: 977548, iterations: 3000, dataset: arabic.txt
   0.544 ins/byte,    0.215 cycle/byte,   15.770 GB/s (1.8 %),     3.397 GHz,    2.527 ins/cycle
   0.624 ins/char,    0.247 cycle/char,   13.760 Gc/s (1.8 %)     1.15 byte/char
```

So I am getting nearly 16 GB/s at 3.4 GHz. You have a 2.6 GHz machine so let us take that down a notch: you should get 12.3 GB/s.



You report 7.5 GB/s. That's low. I can't imagine why you are under 10 GB/s.

Your numbers are more in line with the westmere kernel (which is almost twice as slow).

For fun, I just moved to a `c6i` node on AWS, and I get the following...

```
$ ./build/benchmarks/benchmark -P validate_utf8+icelake -F arabic.txt
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
validate_utf8+icelake, input size: 977548, iterations: 3000, dataset: arabic.txt
  26.976 GB/s (7.5 %)   23.536 Gc/s     1.15 byte/char
```

So 26 GB/s.

I have had a quick look at your code and I cannot spot anything wrong at a glance.

**Comment by Nugine** [comment]
My local machine gives a different result. (I'll write a setup guide later)

```
cd simd-benches
just bench dynamic utf8 utf8-check
just bench static-unstable utf8 utf8-check
./scripts/print-env.sh
```

<details>
<summary>Benchmark Results</summary>

### utf8-check (GiB/s)

#### dynamic (runtime selection)

|                      | Arabic.html   | Chinese.html   | English.html   | French.html   | Russian.html   | Spanish.html   |
|----------------------|---------------|----------------|----------------|---------------|----------------|----------------|
| simdutf8/auto        | 11.559        | **13.062**     | 41.534         | 12.608        | 10.735         | 16.947         |
| simdutf/auto         | **12.432**    | 12.451         | **46.531**     | **13.626**    | **11.159**     | **17.255**     |
| encoding_rs/fallback | 1.661         | 2.476          | 15.030         | 3.838         | 1.552          | 4.814          |
| std/fallback         | 1.449         | 1.892          | 15.801         | 3.458         | 1.348          | 4.326          |

#### static-unstable (-C target-cpu=native)


|                      | Arabic.html   | Chinese.html   | English.html   | French.html   | Russian.html   | Spanish.html   |
|----------------------|---------------|----------------|----------------|---------------|----------------|----------------|
| simdutf8/auto        | **13.485**    | **14.722**     | 42.321         | **13.556**    | **12.099**     | **18.704**     |
| simdutf/auto         | 12.530        | 12.453         | **46.390**     | 13.449        | 11.141         | 17.210         |
| encoding_rs/fallback | 2.207         | 3.697          | 30.355         | 6.475         | 2.143          | 9.499          |
| std/fallback         | 1.448         | 1.886          | 15.627         | 3.361         | 1.342          | 4.195          |

## Environment

COMMIT: fd418c7

Rust:
rustc 1.70.0-nightly (2eaeb1eee 2023-04-05)
binary: rustc
commit-hash: 2eaeb1eee1b21772de8b935236d16ff8e03fdcf5
commit-date: 2023-04-05
host: x86_64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 16.0.0

System:
Linux Nugine-Ub2 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

CPU:
model name	: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz

</details>

And the simdutf benchmark

```
sudo ./build/benchmarks/benchmark -P validate_utf8+haswell -F arabic.txt
```

```
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as haswell
===========================
validate_utf8+haswell, input size: 977526, iterations: 3000, dataset: arabic.txt
   0.545 ins/byte,    0.313 cycle/byte,   13.070 GB/s (2.7 %),     4.093 GHz,    1.739 ins/cycle 
   0.624 ins/char,    0.359 cycle/char,   11.403 Gc/s (2.7 %)     1.15 byte/char 
```

[simd-benches](https://github.com/Nugine/simd-benches/) is running by github actions.
https://github.com/Nugine/simd-benches/blob/main/.github/workflows/benchmark.yml#L54-L55

I guess the performance of github runner may be not stable enough.

**Comment by lemire** [comment]
@Nugine These numbers are more what I expect.
